---

- name: Prepare hosts
  become: true
  remote_user: joris
  hosts: all
  tasks:

    - name: Create ansible user
      ansible.builtin.user:
        name: ansible
        create_home: true
        shell: /bin/bash
        state: present

    - name: Allow ansible user to use sudo without needing a password
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Copy authorized_keys from root user
      ansible.builtin.copy:
        remote_src: true
        src: /root/.ssh
        dest: /home/ansible/
        owner: ansible
        group: ansible
        mode: '0700'
