---

- name: Prepare systems for k8s
  hosts: 'init'
  remote_user: kube
  connection: ssh
  become: true
  become_method: sudo
  tasks:

    - name: Run 'kubeadm reset'
      ansible.builtin.command: "kubeadm reset -f"
      changed_when: true

    - name: Delete CNI configuration
      ansible.builtin.file:
        path: "/etc/cni/net.d"
        state: absent

    - name: Delete created iptables chains
      ansible.builtin.command: iptables -F
      changed_when: true

    - name: Restart tailscaled
      ansible.builtin.systemd:
        name: tailscaled
        state: restarted

# iptables -D INPUT 1 -- deletes first rule from INPUT, usually referencing "KUBE-FIREWALL"
# iptables -D OUTPUT 1 -- deletes first rule from OUTPUT, usually referencing "KUBE-FIREWALL"
# iptables -X KUBE-FIREWALL -- deletes KUBE-FIREWALL chain

