---

- name: Prepare systems for k8s
  hosts: 'control, worker'
  remote_user: kube
  connection: ssh
  become: true
  become_method: sudo
  tasks:

    - name: Delete sysctl.d/99-kube-networking.conf
      ansible.builtin.file:
        path: "/etc/sysctl.d/99-kube-networking.conf"
        state: absent
      register: syctl_changed

    - name: Reload sysctl settings
      ansible.builtin.command: "sysctl --system"
      changed_when: false

    - name: Remove k8s binaries
      ansible.builtin.apt:
        name:
          - kubeadm
          - kubectl
          - kubelet
          - containerd
          - runc
        state: absent

    - name: Remove k8s apt repository
      ansible.builtin.apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        filename: kubernetes
        state: absent
        update_cache: true

    - name: Delete k8s apt key 1
      ansible.builtin.apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: absent

    - name: Delete k8s apt key 2
      ansible.builtin.file:
        path: /usr/share/keyrings/google-cloud.asc
        state: absent

    - name: Delete modules-load.d/containerd.conf
      ansible.builtin.file:
        path: "/etc/modules-load.d/containerd.conf"
        state: absent

    - name: Wipe containerd.conf
      ansible.builtin.file:
        path: "/etc/containerd"
        state: absent

    - name: Delete /etc/kubernetes
      ansible.builtin.file:
        path: "/etc/kubernetes"
        state: absent

    - name: Delete .kube
      ansible.builtin.file:
        path: /home/kube/.kube
        state: absent


    # - name: Import Google Cloud public signing key
    #   become: true
    #   ansible.builtin.command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg
    #   when: "!gc_key_present.exists || (gc_key_downloaded.stat.checksum != gc_key_present.stat.checksum)"
    #   changed_when: true

    # Install containerd:
    # apt install containerd

    # Create default containerd config:
    # containerd config default | sudo tee /etc/containerd/config.toml

    # Edit ONE setting in /etc/containerd/config.toml:
    # nano /etc/containerd/config.toml
    #   DELETE THE LINE that contains: systemd_cgroup
    #   ENSURE that SystemdCgroup is TRUE: "SystemdCgroup = true"

    # Edit /etc/sysctl.conf:
    # - Uncomment "net.ipv4.ip_forward=1" to enable bridging

    # Create/edit /etc/modules-load.d/k8s.conf:
    # - Add line: br_netfilter
    # Save file.

    # Install:
    #   apt install -y ca-certificates curl

    # Download the Google Cloud public signing key:
    #   curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-archive-keyring.gpg

    # Add the kubernetes apt repository:
    #   echo "deb [signed-by=/etc/apt/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list

    # Install kube binaries:
    #   sudo apt update && sudo apt install -y kubeadm kubectl kubelet
    #     # kubeadm helps us create a cluster and join nodes
    #     # kubectl provides command line utility to manage a cluster and interact with it
    #     # kubelet is an agent -- it facilitates communication between nodes

    # Initialize the cluster [MASTER ONLY]:
    #   sudo kubeadm init --control-plane-endpoint=100.104.244.108 --node-name k8s-master --pod-network-cidr=10.244.0.0/16

    # (Save the output)

    # (Copy the config to your local machine)

    # Deploy flannel [LOCAL]:
    #   kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
