---


- name: Update all hosts
  hosts: all
  become: true
  tasks:

    - name: Update package indexes
      ansible.builtin.apt:
        update_cache: true

    - name: Upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        autoclean: true
        autoremove: true
