---

- name: Update all hosts
  hosts: all
  become: true
  remote_user: ansible
  tasks:

    - name: Upgrade to Debian 12
      ansible.builtin.include_role:
        name: deb-upg
      when: "ansible_distribution == 'Debian' and ansible_distribution_version == '11'"

    - name: Upgrade packages
      ansible.builtin.apt:
        update_cache: true
        upgrade: full
        autoclean: true
        autoremove: true

    - name: Configure firewall
      ansible.builtin.include_role:
        name: firewall

    - name: Install default packages
      ansible.builtin.apt:
        name:
          - curl
          - htop
