---

- name: Prepare hosts
  become: true
  hosts: 'init, control, worker'
  tasks:

    - name: Create kube user
      ansible.builtin.user:
        name: kube
        create_home: true
        shell: /bin/bash
        state: present

    - name: Allow kube user to use sudo without needing a password
      ansible.builtin.lineinfile:
        dest: /etc/sudoers
        line: 'kube ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Copy authorized_keys from root user
      ansible.builtin.copy:
        remote_src: true
        src: /root/.ssh
        dest: /home/kube/
        owner: kube
        group: kube
        mode: '0700'
