---

- name: Stop etcd
  ansible.builtin.systemd_service:
    name: etcd
    state: stopped

- name: Delete etcd state
  ansible.builtin.file:
    path: /var/lib/etcd/default
    state: absent

- name: Delete etcd systemd unit override
  ansible.builtin.file:
    path: /etc/systemd/system/etcd.service.d
    state: absent

- name: Create etcd override directory
  ansible.builtin.file:
    path: /etc/systemd/system/etcd.service.d
    state: directory
    mode: "0644"

# - name: Collect Tailscale IPv4 address
#   ansible.builtin.command:
#     cmd: "tailscale ip --4"
#   register: ts_ipv4
#   changed_when: false
#   when: inventory_hostname != groups['etcd'][0]

- name: Install etcd config template
  ansible.builtin.template:
    src: templates/systemd/etcd-join.conf.j2
    dest: /etc/systemd/system/etcd.service.d/override.conf
    mode: "0644"
  register: conf

- name: Restart etcd
  ansible.builtin.systemd:
    name: etcd
    state: restarted
    daemon_reload: true
