---

- name: Install ufw
  ansible.builtin.apt:
    name:
      - ufw
    state: present

- name: Allow incoming on tailscale0
  community.general.ufw:
    interface_in: tailscale0
    rule: allow

- name: Default deny incoming
  community.general.ufw:
    default: deny
    direction: incoming

- name: Default allow outgoing
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Reload and enable ufw
  community.general.ufw:
    state: enabled
