---

- name: Update sources.list from Debian 11 Bullseye to Debian 12 Bookworm
  ansible.builtin.replace:
    regexp: '^(.*)bullseye(.*)$'
    replace: '\1bookworm\2'
    path: /etc/apt/sources.list
  when: "ansible_distribution == 'Debian' and ansible_distribution_version == '11'"

- name: Upgrade system from Debian 11 to Debian 12
  ansible.builtin.apt:
    update_cache: true
    upgrade: full
    autoclean: true
    autoremove: true
  when: "ansible_distribution == 'Debian' and ansible_distribution_version == '11'"
  notify: Reboot
